### ISSUE TITLE
Idle crafters still accept items

### ISSUE THREAD

**Issue by freopt** [Astavie/ThermalLogistics#13]
basically i had a crafter that was not active that had a recipe for planks from wood. then i added some wood into the system via terminal and it went straight into the crafting block connected to the crafter on the itemduct instead of the inventory

**Comment by Astavie** [comment]
1. You can't deactivate crafters
2. Isn't it supposed to go to the block the crater is connected to? What is the "inventory" you speak of?

**Comment by Astavie** [comment]
Oh wait I think I get it - yeah crafters accept any item they have as input even if they aren't doing anything.
