### ISSUE TITLE
Retriever blocks terminal from accessing an inventory

### ISSUE THREAD

**Issue by ProspectPyxis** [Astavie/ThermalLogistics#14]
I tried setting up a pipe network that will put all cobblestone into a separate inventory using a retriever, but this creates a problem, as the retriever seems to make the terminal completely ignore the inventory. Attaching a pipe to another side wouldn't work, as it would cause the cobblestone to endlessly loop around.

**Comment by Astavie** [comment]
That is because Thermal Dynamics does not allow items to be pulled from a retriever. Retrievers only accept items, not distribute it.

**Comment by Astavie** [comment]
Sorry, did not mean to close it

**Comment by ProspectPyxis** [comment]
So the thing to do then would be to use a requester? What I'm worried about then is that if there's a crafter that outputs cobblestone, it'll be getting requests for some when I don't want it.

**Comment by Astavie** [comment]
Maybe you can use a servo and a filter?

**Comment by Astavie** [comment]
Requesters have the same problem as retrievers I think in that regard.

**Comment by ProspectPyxis** [comment]
I see, that would probably work. Thank you.
