### ISSUE TITLE
Dont know if .17 fixed this but terminal isnt placable

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Astavie/ThermalLogistics#17]
Is it not a block because it is not placable. Yes this is the block one

**Comment by Astavie** [comment]
What version? versions 0.1-x need the terminal to be placed on a duct

**Comment by hron84** [comment]
You should not make this as a strong requirement. What if I only can place ducts later? Will the terminal drop if I dismantle the duct behind it (for example replacing it with a better one)? Yes, terminal is only usable if there is a duct connected but terminal block itself should not bind placement permission to ducts.

**Comment by Astavie** [comment]
You're forgetting that in 0.2 terminals can be placed wherever now

**Comment by Astavie** [comment]
Interpreting as duplicate of #7
