### ISSUE TITLE
Inconsistent Crafting

### ISSUE THREAD

**Issue by chrysillis** [Astavie/ThermalLogistics#18]
**Expected behaviour:**
Request 64 wooden planks, receive 64 wooden planks

**Actual behaviour:**
Receive 28 wooden planks with 36 more pending requests. Requests never complete unless item ducts are broken and replaced.

Once this happens, even if the request queue is cleared, it refuses to craft or send anymore items until the pipes are broken and rebuilt.

Breaking all pipes between storage, terminal, and assembly, then redoing them all, will allow it to craft 64 wooden planks successfully, but only once. Then it won't craft anything else again.

**Screenshot 1:**
![image](https://user-images.githubusercontent.com/20598834/54656503-1c734b80-4a83-11e9-9a80-7e8195c9b5b4.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/20598834/54656533-43ca1880-4a83-11e9-9cd9-4062f3bf2538.png)

**Screenshot 3**
![image](https://user-images.githubusercontent.com/20598834/54656552-593f4280-4a83-11e9-9229-349b81e9f7a8.png)

**Comment by Astavie** [comment]
I'm sorry, but I'm not able to reproduce this issue. Do you have a world download?

**Comment by Trinsdar** [comment]
I seem to have gotten a similar problem

**Comment by Astavie** [comment]
@Trinsdar Could you provide more information, please?

**Comment by Trinsdar** [comment]
Testing in an instance with only themal mods and logistics, I can request a craft of something once, but afterwards it gets stuck in que forever next time I try to craft something.

**Comment by Trinsdar** [comment]
@Astavie here's a world download, using just thermal expansion, foundation, dynamics, and logistics
[thermal.zip](https://github.com/Astavie/ThermalLogistics/files/3091331/thermal.zip)

**Comment by Astavie** [comment]
@Trinsdar your set-up is not correct, and I'm afraid the same may count for @DarkSylph. To register that an item has been produced, it needs to go through a crafter again. This can easily be done by making the input side also the output side. What you have done is set the output to a side without a crafter. The item just so happens to arrive in the terminal, and meanwhile, the crafter still thinks its process is ongoing.

**Comment by Astavie** [comment]
Given that this is a recurring misconception, I'll add some documentation (both here and ingame)
