### ISSUE TITLE
Crash when opening terminal

### ISSUE THREAD

**Issue by BillboardEric** [Astavie/ThermalLogistics#2]
If the terminal is placed next to an item duct by placing it on a nearby block rather than the item duct itself, not only will it not connect to the pipe, but it will crash the game if you try to open it. 

Log here:
https://paste.dimdev.org/ledifowupe.mccrash

**Comment by Astavie** [comment]
I'm on a roll today with these crashes. For now just place the terminal on the duct (that's how you're supposed to place it)

**Comment by Astavie** [comment]
Alright fixed in 0.1-9
