### ISSUE TITLE
Is this part of TL?

### ISSUE THREAD

**Issue by Yeuaak** [Astavie/ThermalLogistics#27]
I have been trying to figure out what has been causing this. But it only happens when I try to add a recipe into the terminal. Sorry in advance if this isn't Thermal Logistics. 
FTB: Interactions ver 1.4.2  
![image](https://user-images.githubusercontent.com/47170228/57116608-395a9a00-6d24-11e9-9063-908038a77344.png)

**Comment by Astavie** [comment]
That is both TL and JEI working together :D It's a feature. If you want to craft that block, you can press 'r' (or whatever hotkey you have) instead of clicking on it.
