### ISSUE TITLE
Recipes get bugged when craft in the Terminal

### ISSUE THREAD

**Issue by Azami1990** [Astavie/ThermalLogistics#28]
**Overview**

When you craft an Item in the Terminal it buggs the Recipe for the whole Server and its not craftable anymore until Server restart.
When the Recipe is bugged the Terminal just "eats" the Items and won't give you the Output, Vanilla Table won't show a valid Recipe (no Output at all) and Tinkers Table shows a valid Recipe but you can't take the Item. Shift-Click will show it in your Inventory but as soon as you close the Tinkers Table UI its gone and the Materials are back in the Table.

By now i just got the bug when i requested all items in the Terminal. When you put some Items manually i in the Terminal it didn't happened.
If you need Logs, i'm sure Thorgal can give me/you the logs.

**To Reproduce**

Here is a Video of me reproducing the bug:
https://cdn.discordapp.com/attachments/575448826245152798/575802361373523970/ThermalLogistics_bug.webm

**Versions**

 - Minecraft 1.12.2
 - Forge 14.23.5.2836
 - CoFH Core 4.6.2.25
 - CoFH World 1.3.0.6
 - Thermal Foundation 2.6.2.26
 - Thermal Expansion 5.5.3.41
 - Thermal Dynamics 2.5.4.18
 - Thermal Logistics 0.2-23
 - Modpack: Rails and Pipes by FTOG_Thorgal on Twitch/Curse

**Comment by Azami1990** [comment]
Its als reproducable in Singleplayer.
Log shows nothing. Just basic login and stopping the server
https://drive.google.com/open?id=1m4r0RCZKE8CqrUnX8sVVa_PfxJz8tpun

**Comment by SFort** [comment]
Using something like [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench) the recepie does not even show up after this bug. So I'm assuming the recepie gets removed untill server reboot
