### ISSUE TITLE
Suggestion for info.

### ISSUE THREAD

**Issue by BillboardEric** [Astavie/ThermalLogistics#3]
Would love to see an info button like traditional thermal mods have to describe how to use the terminal. Right now everything is guess work, and I assume you are working on documentation, but an in-game feature for that would be nice rather than just guide on the mod page

**Comment by Astavie** [comment]
Yeah I'll work on that

**Comment by Astavie** [comment]
There is now a wiki https://github.com/Astavie/ThermalLogistics/wiki
