### ISSUE TITLE
[Suggestion] Terminal tick delay

### ISSUE THREAD

**Issue by SFort** [Astavie/ThermalLogistics#30]
Would you consider making the terminal scan the network less frequently.(or whatever it's doing to rack up a process time of ~4ms / tick)
it takes this long even when it's not doing anything or when no player is interfacing with it.
In my case it's connected to a system with about 30 containers & 20 crafters
It only has sutch a long process time when there's a requester in it. 
otherwise the time is about 1µs / tick
Might i suggest a tick delay proportional to network size or something of the sort?

Thermal Logistics 0.2-25
[laggoggles](https://minecraft.curseforge.com/projects/laggoggles/files/2536205)(to get the process time /tick)

**Comment by Astavie** [comment]
There is a config option for this

**Comment by SFort** [comment]
"The amount of ticks delay between sync packets from the server when looking at a GUI."
as i understand it this option only affects client-server communication not actual server performance.
and as i said the process time remains the same weather a player is interacting with it or not

**Comment by Astavie** [comment]
Counting this as a bug then, the terminal has no reason to take up that much time

**Comment by SFort** [comment]
Thanks, if you want any further details / world etc. do tell

**Comment by Astavie** [comment]
Version 0.3 just dropped, which is basically a rewrite. This should hopefully fix any issues with the terminal taking up too much processing time!
