### ISSUE TITLE
Weird bug with thermal covers

### ISSUE THREAD

**Issue by avidgamer5918** [Astavie/ThermalLogistics#33]
**Overview**
When trying to craft covers from thermal expansion and gives you an errored version of it.

**To Reproduce**
In the terminal try to craft a cover from Thermal Expansion

1. Open a terminal 
2. Craft a cover from Thermal Expansion
3. See error

**Expected behavior**

crafts cover without a problem

**Screenshots**
https://gyazo.com/687f0912091bbb9faaaec76d84a22934
https://gyazo.com/629086fa1ab228aea58305a7bef1fc34

**Versions**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - CoFH Core: 4.6.3.27
 - CoFH World: 1.3.1.7
 - Thermal Foundation: 6.3.27
 - Thermal Expansion: 5.5.4.43
 - Thermal Dynamics: 2.5.5.21
 - Thermal Logistics: 0.2-26

**Comment by Krougal** [comment]
I can verify this as well.
Do you have covers hidden from JEI on/off? (config option, they are actually Thermal Dynamics not TE) I have them hidden. Just thinking if it may be related or not. They craft fine from vanilla crafting bench. I thought maybe it was just a creative mode thing when it happened to me.
