### ISSUE TITLE
Crash & world corruption when deleting an in use linked crafter

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#34]
**Overview**

Crash & world corruption when deleting an in use crafter. Crash I mentioned on Curseforge that I said I would provide the log for.

**To Reproduce**

1. Remove duct with in use linked crafter in creative. Sorry I have not gotten around to trying to repoduce in survival or otherwise.

https://pastebin.com/BEv5926c

**Comment by Astavie** [comment]
Should be fixed now in 0.2-27, you can try opening a previously corrupted world, since they should be uncorrupted now.

**Comment by Krougal** [comment]
> Should be fixed now in 0.2-27, you can try opening a previously corrupted world, since they should be uncorrupted now.

PFM...old corrupted save loaded up. Good job sir
