### ISSUE TITLE
Crash again, slightly different this time

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#37]
**Overview**

Deleted Redstone furnace that had crafters attached on ducts, was not in use at the time.
World corrupted as well again.

https://paste.dimdev.org/poziqihuzo.mccrash - initial crash

https://paste.dimdev.org/xonesidaba.mccrash - crash reloading

I know the fix for the other issue worked. I double-checked this instance is patched (cause first time was other)

**Comment by Astavie** [comment]
Should be fixed in 0.2-28 (you should be able to enter the world again)

**Comment by Krougal** [comment]
Confirmed.
