### ISSUE TITLE
[Suggestion] Add the Add Fluid dialogue to Requester attachment

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#38]
When using the requester attachment on a fluid duct, there is no way to add the fluid outside of buckets, which I am not sure works properly (it does work in some conditions at least, but I am still determining if it is as intended or by accident). The way it is implemented on the crafter is very nice.

**Comment by Astavie** [comment]
The requester just uses the GUI of the retriever, and in there you insert a bucket/bottle/any item with a fluid inside. If you're noticing that the requester isn't working properly I'd love a bug report.

**Comment by Krougal** [comment]
I'm still figuring out the proper setup for what I am trying to do, so it may just be a PEBKAC.
Like I said, it is working at the moment, but I'm not positive if it is just getting input because it is being pushed or because it is being pulled. Will file bug report if it isn't working right. I guess you can close this since it's not needed.
