### ISSUE TITLE
[Suggestion] Crafter linking to specific recipe slots

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#39]
I'll just give a use case since it's probably easier to understand, not to mention explain.

Resonant crafter, item duct to fluid transposer. Linked to resonant crafter on fluid duct to same transposer. Produces the 3 types of filled  fluxducts, (need 200mB), RA fluxed-electrum & crystal (both need 500mB) and let's say also fills buckets on demand (1000mB).

The fluid linked crafter only needs destabilized redstone, but we need different amounts for each linked recipe. Currently it's an all or nothing thing. It's even worse if you try this with multiple types of inputs, since any recipe that triggers will trigger all inputs simultaneously.

I realize this may be more trouble than it is worth, since it could produce more crashes/general ability to jam the system so it might require a lot of error-trapping, but if it's easy then it would be a very good feature.

Maybe something similar in function to how LP can link satelite pipes by number, but less clunky and more elegant in implementation.

**Comment by Astavie** [comment]
Have you read https://github.com/Astavie/ThermalLogistics/wiki/Crafter#linking-with-multiple-recipes ? The way you describe linking is not how it actually works.

**Comment by Krougal** [comment]
No, and I feel like an idiot for overlooking the fact that you have a wiki (considering I had to figure everything out by myself).

So what I am requesting is already a feature. It has not seemed to work this way, I have seen some real wierdness but it is possible the order I created and linked recipes was not correct. I will doublecheck and get back to you.

**Comment by Krougal** [comment]
Yes, it was me. This is working perfectly right now.

**Comment by Krougal** [comment]
Oh, I remember now what my problem was the other day.
I was trying to link multiple basic crafters to a single resonant. So the single crafters were requesting different magma crucible outputs, and the 1 resonant was feeding all the different input materials in..
Would be awesome if it worked, but I can understand where it is such an edge case it probably isn't worth the effort. And I think I already figured a work-around for that one, the fluid-allocator actually IS useful.

**Comment by Krougal** [comment]
Here is another edge case:
Signalum crafter, 4 recipes, basalz/blizz/blitz/blaze powderson a fluid transposer. They each also use the same 200mB of liquid knowledge, so in theory a basic crafter would be able to supply all 4, but it requires a signalum with 4 identical recipes (or just skip the fluid crafter and keep the thing full). Not a huge deal.  Really only an early game issue I guess, and automation isn't an early game activity.
Again, this feature might be more trouble than it is worth if these are the most compelling cases I can think of.

**Comment by Astavie** [comment]
This has been addressed in 0.3, a version I'm currently working on. You will have finer control over which recipes are linked to each other. An alpha version might be available soon.
