### ISSUE TITLE
Linked Crafter crash & corruption (3rd try)

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#40]
**Overview**

I did it again. We will make this thing bulletproof yet. Decided I needed to move linked crafter over 1 slot, so redprinted, smashed pipe (on purpose this time) and boom.

Initial:
https://paste.dimdev.org/uqenazogoc.mccrash
Attempt to reload:
https://paste.dimdev.org/ewafeludej.mccrash

**Comment by Astavie** [comment]
Oh boy... This is basically #34 but with fluids.

**Comment by Astavie** [comment]
Hopefully fixed in 0.2-29

**Comment by Krougal** [comment]
Will confirm when Twitch stops being retarded. Even manually downloading and overwriting with 29 the POS client doesn't want to move off 28. Curse was so much better before Twitch merger...

**Comment by Krougal** [comment]
And we are good to go.
