### ISSUE TITLE
Terminal and Crafter GUIs misaligned with "Faithful 32 Modded Edition" texture pack

### ISSUE THREAD

**Issue by pat2rome** [Astavie/ThermalLogistics#57]
**Overview**

The GUI for the Terminal and for Crafters become misaligned when using the "Faithful 32 Modded Edition" texture pack. I know texture pack issues may not be a concern of yours but this one is in extremely common use.

![Terminal GUI](https://i.imgur.com/ZaXcWlp.png)

![Crafter GUI](https://i.imgur.com/8Zn5i0V.png)

**To Reproduce**

1. Download the resource pack located here: http://www.f32.me/F32-1.12.2.zip
2. Load the resource pack in the game.
3. Use a Terminal or a Crafter in-game (mode does not matter).

**Expected behavior**

![Terminal GUI](https://i.imgur.com/w9aYPCh.png)

![Crafter GUI](https://i.imgur.com/vfErJG5.png)

**Versions**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2855
 - CoFH Core: 4.6.6.1
 - CoFH World: 1.4.0.1
 - Thermal Foundation: 2.6.7.1
 - Thermal Expansion: Bug still occurs with no version of this installed
 - Thermal Dynamics: 2.5.6.1
 - Thermal Logistics: 0.3-43

**Additional context**

I have confirmed this happens both without JEI/NEI installed, as well as with JEI and several addons, so interactions between the GUI and JEI are not the cause. This also happens with or without the original Faithful 32 texture pack (which covers vanilla textures), so the cause is not the change in font introduced in that resource pack. The culprit is certainly somewhere in the Faithful 32 Modded Edition resource pack.

**Comment by pat2rome** [comment]
Someone brought this to their attention via their own GitHub repo back in January (https://github.com/F32Organization/Faithful32-1.12.2/issues/219), but they received no acknowledgement and the issue still persists, so I figured I would give you a heads up too.

**Comment by Astavie** [comment]
I was aware of this issue, the faithful textures were based on versions 0.2.x, while we are now on 0.3.x. Unfortunately, there is little I can do to fix it. Someone will have to make a pull request on the faithful resource pack.

**Comment by pat2rome** [comment]
> I was aware of this issue, the faithful textures were based on versions 0.2.x, while we are now on 0.3.x. Unfortunately, there is little I can do to fix it. Someone will have to make a pull request on the faithful resource pack.

Thanks, I figured it might not be anything you could do something about. Time to go dig through and see who originally added the mod to the pack and make sure they know things are messed up now!
