### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by tjsd** [Astavie/ThermalLogistics#6]
forge             | 14.23.5.2811
thermallogistics  | 0.1-11 
thermalfoundation | 2.6.2 
thermaldynamics   | 2.5.4

Crash:
https://pastebin.ubuntu.com/p/TTQWbHWGMg/

**Comment by tjsd** [comment]
Looking at it, it seems it searches for Thermal Expantion, that is not in the pack, if it is a requirement it should be listed as such on curse so you have to install it. I was hoping to use the ducts and the mod without the Expantion machines but with other mods.

**Comment by Astavie** [comment]
OH I didn't realise the machine frame was from Thermal Expansion! (usually these things are in Thermal Foundation) I'll add it as a required dependency then.

**Comment by Astavie** [comment]
Done

**Comment by tjsd** [comment]
There are redstone servo and coils in foundation. Maybe you could list those as alternatives if there is no expantion?

**Comment by Astavie** [comment]
0.1-12 has no dependency on TE anymore. without TE the machine frame is replaced with an iron block
